sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 646600893
  alioss:
    bucket-name: project1hqy
    access-key-secret: DdXVYt7Pju8pD6vrzBWBNSOmYtae2r
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tGbdCFVvB5Tq5pn2WMS
